import type { en, TranslationShape } from './en';

export const ru: TranslationShape<typeof en> = {
  common: { save: 'Сохранить', cancel: 'Отмена', close: 'Закрыть', retry: 'Повторить', delete: 'Удалить', edit: 'Изменить', duplicate: 'Копировать', create: 'Создать', add: 'Добавить', done: 'Готово', confirm: 'Подтвердить', moveUp: 'Переместить выше', moveDown: 'Переместить ниже', kg: 'кг', lb: 'фунт' },
  nav: { home: 'Главная', programs: 'Программы', start: 'Старт', history: 'История', progress: 'Прогресс' },
  app: { loading: 'Загружаем данные…', databaseError: 'Не удалось открыть локальные данные.' },
  home: { title: 'FitnessMate', greeting: 'Готовы тренироваться?', noWorkouts: 'Завершённые тренировки появятся здесь.', weeklyVolume: 'Объём за неделю', workouts: 'Тренировки', resumeDraft: 'Продолжить тренировку' },
  programs: { title: 'Программы', emptyTitle: 'Программ пока нет', emptyBody: 'Создайте многоразовую программу тренировки.', new: 'Новая программа', name: 'Название программы', description: 'Описание', exercises: 'Упражнения', sets: 'подходов', exerciseCount: 'упражнений', deleteTitle: 'Удалить программу?', deleteBody: 'Программа будет удалена. История тренировок не изменится.', notFound: 'Программа не найдена.', nameRequired: 'Введите название программы.', exerciseRequired: 'Добавьте хотя бы одно упражнение.', remove: 'Удалить программу', reorderHint: 'Зажмите и перетащите, чтобы изменить порядок программ' },
  editor: { addExercise: 'Добавить упражнение', addSet: 'Добавить подход', removeExercise: 'Удалить упражнение', removeSet: 'Удалить подход', duplicateSet: 'Копировать подход', weight: 'Вес', reps: 'Повторы', setNumber: 'Подход {{number}}', chooseExercise: 'Выберите упражнение', searchExercise: 'Поиск упражнений', customExercise: 'Создать своё упражнение', customName: 'Название упражнения', muscleGroup: 'Группа мышц' },
  start: { title: 'Начать тренировку', choose: 'Выберите программу или начните пустую тренировку.', emptyWorkout: 'Пустая тренировка', unfinished: 'Ведение тренировки будет доступно на следующем этапе.' },
  workout: { defaultName: 'Тренировка', noActive: 'Нет активной тренировки', finish: 'Завершить тренировку', finishTitle: 'Завершить тренировку?', finishBody: 'Выполненные подходы сохранятся в истории.', discard: 'Отменить', discardTitle: 'Удалить черновик?', discardBody: 'Текущая тренировка будет удалена.', completedSets: 'выполненных подходов' },
  history: { title: 'История', emptyTitle: 'История пуста', emptyBody: 'Завершите тренировку, чтобы увидеть её здесь.', volume: 'Объём', share: 'Поделиться', deleteTitle: 'Удалить тренировку?', deleteBody: 'Тренировка будет удалена безвозвратно.' },
  progress: { title: 'Прогресс', emptyTitle: 'Нет данных', emptyBody: 'Завершите тренировки, чтобы открыть аналитику.', totalWorkouts: 'Всего тренировок', weeklyVolume: 'Объём за 7 дней', personalRecords: 'Личные рекорды', maxWeight: 'Максимальный вес', maxVolume: 'Лучший объём подхода' },
  settings: { title: 'Настройки', language: 'Язык', units: 'Единицы веса', theme: 'Тема', russian: 'Русский', english: 'Английский', kilograms: 'Килограммы', pounds: 'Фунты', system: 'Системная', light: 'Светлая', dark: 'Тёмная', data: 'Данные', export: 'Экспорт резервной копии', import: 'Импорт резервной копии', clear: 'Очистить все данные', clearTitle: 'Очистить все данные?', clearBody: 'Программы, тренировки, история и свои упражнения будут удалены.', replace: 'Заменить текущие данные', merge: 'Объединить с текущими данными', exportSuccess: 'Резервная копия создана', importSuccess: 'Резервная копия импортирована', invalidBackup: 'Файл не является резервной копией FitnessMate.', aboutOffline: 'Все данные хранятся только на этом устройстве. Аккаунт и интернет не нужны.' },
  muscleGroups: { chest: 'Грудь', back: 'Спина', legs: 'Ноги', shoulders: 'Плечи', arms: 'Руки', core: 'Кор', other: 'Другое' },
  exercises: { barbellBenchPress: 'Жим штанги лёжа', squat: 'Приседания', deadlift: 'Становая тяга', overheadPress: 'Жим над головой', barbellRow: 'Тяга штанги в наклоне', pullUp: 'Подтягивания', bicepsCurl: 'Сгибание на бицепс', tricepsExtension: 'Разгибание на трицепс', legPress: 'Жим ногами', calfRaise: 'Подъёмы на носки' },
};
